---
name: ci
on:
  push:
  schedule:
    - cron: '0 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO: phaag/nfdump
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "${{ env.REPO }}"
          clean: true
          fetch-depth: 0
      - id: latest_tag
        run: |
          export LATEST_TAG=$(git describe --tags)
          echo "::set-output name=latest_tag::${LATEST_TAG}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: gnought/docker-nfdump:latest
          labels: |
            org.label-schema.schema-version="1.0"
            org.label-schema.vcs-ref=${{ steps.latest_tag.outputs.latest_tag }}
            org.label-schema.vcs-url=${{ env.REPO }}
